Node > 12 compatibility
```
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- ~/scrivito_example_app_js/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
```

Solution found here:
https://github.com/storybookjs/storybook/issues/10477#issuecomment-619423402